version: "3"

x-var: &GEM_NAME
  mysql_performance_logger

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: mysql
    depends_on:
      - mysql
    volumes: 
      - .:/app:cached
      - bundle:/app/vendor/bundle
        
  mysql:
    image: mysql:8.1
    command: ["--bind-address=0.0.0.0"]
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-volume:/var/lib/mysql

volumes:
  bundle:
  db-volume:
    